### ISSUE TITLE
VCF to Zarr Conversion Fails When Attempting to Convert Certain VCF files

### ISSUE THREAD

**Issue by eauel** [ornl-oxford/genomics-benchmarks#34]
I ran into an issue today when testing the conversion of VCF files downloaded from 1000 Genomes project ([ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/](url)).

Up until this point I have primarily been using a different, smaller test VCF file which was always able to be converted to Zarr successfully.

Below is the error I am receiving when running allel.vcf_to_zarr():

```
Traceback (most recent call last):
  File "./genomics-benchmarks/genomics-benchmark", line 6, in <module>
    cli.main()
  File ".\genomics-benchmarks\benchmark\cli.py", line 124, in main
    _main()
  File ".\genomics-benchmarks\benchmark\cli.py", line 116, in _main
    benchmark.run_benchmark()
  File ".\genomics-benchmarks\benchmark\core.py", line 125, in run_benchmark
    self._benchmark_convert_to_zarr()
  File ".\genomics-benchmarks\benchmark\core.py", line 166, in _benchmark_convert_to_zarr
    benchmark_profiler=self.benchmark_profiler)
  File ".\genomics-benchmarks\benchmark\data_service.py", line 350, in convert_to_zarr
    log=sys.stdout, compressor=compressor)
  File "~\Anaconda3\envs\genomics-benchmarks\lib\site-packages\scikit_allel-1.1.10-py3.6-win-amd64.egg\allel\io\vcf_read.py", line 798, in vcf_to_zarr
    overwrite=overwrite, headers=headers
  File "~\Anaconda3\envs\genomics-benchmarks\lib\site-packages\scikit_allel-1.1.10-py3.6-win-amd64.egg\allel\io\vcf_read.py", line 668, in _zarr_setup_datasets
    compressor=compressor, overwrite=overwrite)
  File "~\Anaconda3\envs\genomics-benchmarks\lib\site-packages\zarr-2.2.0-py3.6.egg\zarr\hierarchy.py", line 772, in create_dataset
  File "~\Anaconda3\envs\genomics-benchmarks\lib\site-packages\zarr-2.2.0-py3.6.egg\zarr\hierarchy.py", line 630, in _write_op
  File "~\Anaconda3\envs\genomics-benchmarks\lib\site-packages\zarr-2.2.0-py3.6.egg\zarr\hierarchy.py", line 785, in _create_dataset_nosync
  File "~\Anaconda3\envs\genomics-benchmarks\lib\site-packages\zarr-2.2.0-py3.6.egg\zarr\creation.py", line 119, in create
  File "~\Anaconda3\envs\genomics-benchmarks\lib\site-packages\zarr-2.2.0-py3.6.egg\zarr\storage.py", line 313, in init_array
  File "~\Anaconda3\envs\genomics-benchmarks\lib\site-packages\zarr-2.2.0-py3.6.egg\zarr\storage.py", line 327, in _init_array_metadata
  File "~\Anaconda3\envs\genomics-benchmarks\lib\site-packages\zarr-2.2.0-py3.6.egg\zarr\errors.py", line 21, in err_contains_array
ValueError: path 'variants/svlen' contains an array
```

**Comment by alimanfoo** [comment]
Hm, there's something funny going on with the svlen field, there's a
different error just been reported on scikit-allel issue tracker. Must be a
bug somewhere.

**Comment by alimanfoo** [comment]
Hi @eauel, are you developing on a windows or mac? This VCF contains an INFO field named 'SVLEN' which will clash with the computed field 'svlen' on case insensitive file systems, more in depth explanation here: https://github.com/cggh/scikit-allel/issues/215#issuecomment-434088283

**Comment by eauel** [comment]
@alimanfoo Yes I am developing on a Windows 10 machine. Thank you for the explanation!
